x-default-opts: &default-opts
  restart: unless-stopped
  tty: true
  stdin_open: true
  privileged: false
  ipc: private

services:
  nginx:
    <<: *default-opts
    image: nginx:latest
    ports:
      - "50001:80"

