x-default-opts: &default-opts
  restart: always
  tty: true
  stdin_open: true
  privileged: false
  ipc: private

services:
  # server 專用 database
  rds-db:
    <<: *default-opts
    image: mariadb:lts-jammy
    container_name: rds-db
    shm_size: 256mb
    ports:
      - ${DATABASE_PORT}:3306
    environment:
      - TZ=UTC
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=main_database
    volumes:
      - ./db/mariadb.cnf:/etc/mysql/mariadb.cnf
      - db:/var/lib/mysql
    networks:
      - rds-server
  # server 專用 redis
  rds-redis:
    <<: *default-opts
    image: redis:7.4.1
    container_name: rds-redis
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      - rds-server
  # server 專用 api
  rds-api:
    <<: *default-opts
    build:
      context: ./api/
      dockerfile: ./Dockerfile
    container_name: rds-api
    volumes:
      - ./api:/app
    networks:
      - rds-server
  # server 專用 nginx
  rds-nginx:
    <<: *default-opts
    image : nginx:stable-perl
    container_name: rds-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/domain:/etc/nginx/sites-enabled
      - static:/static
    ports:
      - "50000:80"
    networks:
      - rds-server
  # vpn 專用 nginx
  rds-proxy:
    <<: *default-opts
    image: nginx:stable-perl
    container_name: rds-proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/domain:/etc/nginx/sites-enabled
    ports:
      - ${PROXY_PORT}:80
    networks:
      - rds-server
      - rds-vpn
  vuetify:
    <<: *default-opts
    image: node:22
    container_name: rds-vuetify
    entrypoint: /bin/sh -c "cd /app && npm install && npm run build && npm run dev"
    volumes:
      - ./vuetify:/app
    networks:
      - rds-server
  
networks:
  rds-server:
    driver: bridge
  rds-vpn:
    external: true
    
volumes:
  db: {}
  static: {}
  proxy-domain: {}