x-default-opts: &default-opts
  restart: always
  tty: true
  stdin_open: true
  privileged: true
  ipc: private

services:
  rds-docker-host:
    <<: *default-opts
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: rds-docker-host
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "52375:80"
    entrypoint: /bin/sh -c "cd /app && gunicorn --bind 0.0.0.0:80 -w 1 -k uvicorn.workers.UvicornWorker main:app"
    networks:
      - rds-docker-host

networks:
  rds-docker-host:
    external: true