name: Test

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Compose
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        compose-file: ./docker-compose.yml
        cwd: ./rds-server/rds-docker-host/
    
    - name: Unit Test
      run: |
        docker exec rds-docker-host bash -c "cd /app && pytest -s"