name: Test

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Compose
      uses: hoverkraft-tech/compose-action@v2.0.1

    - name: Run Docker Compose
      run: |
        cd ./rds-server/rds-docker-host
        docker-compose -f ./docker-compose.yml up -d