name: Test Docker Host

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create Docker Network
      run: |
        docker network create --driver bridge --subnet=10.100.0.0/16 rds-container-pool
        docker network create --driver bridge rds-server
        docker network create --driver bridge rds-docker-host

    - name: Docker Compose
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        compose-file: ./docker-compose.yml
        cwd: ./rds-server/rds-docker-host/
    
    - name: Unit Test
      run: |
        docker pull busybox:latest
        docker exec rds-docker-host bash -c "cd /app && pytest -s"